apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-task-platform-config
  namespace: ai-task-platform
data:
  NODE_ENV: production
  CORS_ORIGIN: https://test
  QUEUE_KEY: ai_tasks
  MONGODB_DB: ai-task-platform
  BACKEND_PORT: "4000"
  WORKER_HEALTH_PORT: "8081"
