apiVersion: v1
kind: Secret
metadata:
  name: ai-task-platform-secrets
  namespace: ai-task-platform
type: Opaque
stringData:
  JWT_SECRET: replace-me
  MONGO_ROOT_USERNAME: aiadmin
  MONGO_ROOT_PASSWORD: replace-me
  MONGODB_URI: mongodb://aiadmin:replace-me@mongo:27017/ai-task-platform?authSource=admin
